#!/usr/bin/env bash
# SEX SLAVE DUNGEON — Mac/Linux local launcher
set -e

cd "$(dirname "$0")"
PROJECT_DIR="$(pwd)"

echo
echo "===================================="
echo "  SEX SLAVE DUNGEON - local launcher"
echo "===================================="
echo
echo "Project: $PROJECT_DIR"
echo

# --- Sync .env -> js/env.local.js --------------------------------------
# .env is the single source of truth for local dev. js/env.local.js is the
# browser-loaded artifact (both gitignored). Re-runs cheaply every launch.
echo "[0/3] Syncing .env to js/env.local.js..."
sync_env() {
  local envfile="$PROJECT_DIR/.env"
  local outfile="$PROJECT_DIR/js/env.local.js"
  if [ ! -f "$envfile" ]; then
    echo "  - No .env at project root — skipping sync."
    return 0
  fi
  local count=0
  {
    echo "// SEX SLAVE DUNGEON — local dev env (AUTO-GENERATED from .env — GITIGNORED)"
    echo "// Do not edit this file directly. Edit .env at the project root and re-run start.bat / start.sh."
    echo "// On deployment this file does not exist; the visitor supplies values via the landing-page Settings panel."
    echo "window.__DEV_ENV = {"
    local first=1
    while IFS= read -r raw || [ -n "$raw" ]; do
      local line="${raw%$'\r'}"
      # skip blank lines + comments
      case "$line" in
        ''|\#*) continue ;;
      esac
      # split on first =
      case "$line" in
        *=*) : ;;
        *) continue ;;
      esac
      local key="${line%%=*}"
      local val="${line#*=}"
      # trim whitespace from key + val
      key="$(printf '%s' "$key" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
      val="$(printf '%s' "$val" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
      # strip a single layer of surrounding quotes
      case "$val" in
        \"*\") val="${val#\"}"; val="${val%\"}" ;;
        \'*\') val="${val#\'}"; val="${val%\'}" ;;
      esac
      [ -z "$key" ] && continue
      if [ $first -eq 1 ]; then first=0; else printf ',\n'; fi
      if [ "$val" = "true" ] || [ "$val" = "false" ]; then
        printf '  %s: %s' "$key" "$val"
      else
        local esc="${val//\\/\\\\}"
        esc="${esc//\'/\\\'}"
        printf "  %s: '%s'" "$key" "$esc"
      fi
      count=$((count + 1))
    done < "$envfile"
    printf '\n'
    echo "};"
  } > "$outfile"
  echo "  + Synced .env → js/env.local.js ($count vars)"
}
sync_env || echo "  ! Sync failed (non-fatal). Browser falls back to existing js/env.local.js or settings panel."
echo

# --- Ollama check + auto-start ----------------------------------------
echo "[1/3] Checking Ollama..."
if command -v ollama >/dev/null 2>&1; then
  echo "  + Ollama found."
  export OLLAMA_ORIGINS="*"

  if curl -sSf --max-time 2 http://localhost:11434/api/tags >/dev/null 2>&1; then
    echo "  + Ollama already running at localhost:11434"
  else
    echo "  + Launching Ollama in the background..."
    ( OLLAMA_ORIGINS="*" nohup ollama serve >/tmp/ssd-ollama.log 2>&1 & )
    sleep 4
  fi
else
  echo "  X Ollama not found on PATH."
  echo "  Download from https://ollama.com/download before girls can talk."
fi
echo

# --- Find a static server --------------------------------------------
echo "[2/3] Finding a local web server..."
SERVER_CMD=""
SERVER_LABEL=""

if command -v python3 >/dev/null 2>&1; then
  SERVER_CMD="python3 -m http.server 8080"
  SERVER_LABEL="Python 3 http.server"
elif command -v python >/dev/null 2>&1; then
  SERVER_CMD="python -m http.server 8080"
  SERVER_LABEL="Python http.server"
elif command -v npx >/dev/null 2>&1; then
  SERVER_CMD="npx --yes http-server . -p 8080 -c-1 --cors"
  SERVER_LABEL="Node npx http-server"
elif command -v php >/dev/null 2>&1; then
  SERVER_CMD="php -S localhost:8080"
  SERVER_LABEL="PHP built-in server"
else
  echo
  echo "  X No local web server found."
  echo "  Install ONE of these so the game can be served over HTTP:"
  echo "    - Python 3:  https://python.org/downloads/"
  echo "    - Node.js:   https://nodejs.org/"
  echo "    - PHP:       brew install php  (Mac) or apt install php (Linux)"
  echo
  exit 1
fi

echo "  + Using: $SERVER_LABEL"
echo

# --- Open browser + start server -------------------------------------
echo "[3/3] Starting server on http://localhost:8080"
echo "      Opening browser in 2 seconds..."
echo

( sleep 2
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open http://localhost:8080/index.html
  elif command -v open >/dev/null 2>&1; then
    open http://localhost:8080/index.html
  fi ) &

echo "===================================================="
echo "  Server running at http://localhost:8080"
echo "  Landing: http://localhost:8080/index.html"
echo "  Game:    http://localhost:8080/game.html"
echo "  Ctrl-C to stop."
echo "===================================================="
echo

exec $SERVER_CMD
