# DUNGEON MASTER: THE HUNT -- .env to js/env.local.js sync (Windows / PowerShell)
#
# Reads the project-root .env, regenerates js/env.local.js so the browser-side
# window.__DEV_ENV always reflects the latest .env values. Idempotent: re-run any
# time you change .env. Called by start.bat as Step 0.
#
# Both files are gitignored. .env is the single source of truth for local dev.

$ErrorActionPreference = 'Stop'

$projectDir = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $projectDir '.env'
$outFile = Join-Path $projectDir 'js\env.local.js'

if (-not (Test-Path -LiteralPath $envFile)) {
    Write-Host "  - No .env at project root -- skipping sync. Browser uses existing js/env.local.js or settings panel."
    exit 0
}

$pairs = @()
$rawLines = Get-Content -LiteralPath $envFile -Encoding UTF8
foreach ($rawLine in $rawLines) {
    if ($null -eq $rawLine) { continue }
    $line = ([string]$rawLine).Trim()
    if ($line.Length -eq 0) { continue }
    if ($line.StartsWith('#')) { continue }
    $eq = $line.IndexOf('=')
    if ($eq -lt 1) { continue }
    $key = $line.Substring(0, $eq).Trim()
    $val = $line.Substring($eq + 1).Trim()
    if ($val.Length -ge 2) {
        $first = $val.Substring(0, 1)
        $last = $val.Substring($val.Length - 1, 1)
        if (($first -eq '"' -and $last -eq '"') -or ($first -eq "'" -and $last -eq "'")) {
            $val = $val.Substring(1, $val.Length - 2)
        }
    }
    if ($key.Length -eq 0) { continue }
    $pairs += ,([PSCustomObject]@{ Key = $key; Val = $val })
}

if ($pairs.Count -eq 0) {
    Write-Host "  - .env had no key=value entries -- skipping write."
    exit 0
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// DUNGEON MASTER: THE HUNT -- local dev env (AUTO-GENERATED from .env -- GITIGNORED)')
[void]$sb.AppendLine('// Do not edit this file directly. Edit .env at the project root and re-run start.bat / start.sh.')
[void]$sb.AppendLine('// On deployment this file does not exist; the visitor supplies values via the landing-page Settings panel.')
[void]$sb.AppendLine('window.__DEV_ENV = {')

for ($i = 0; $i -lt $pairs.Count; $i++) {
    $k = $pairs[$i].Key
    $v = $pairs[$i].Val
    if ($v -eq 'true' -or $v -eq 'false') {
        $jsVal = $v
    } else {
        $escaped = $v.Replace('\', '\\').Replace("'", "\'")
        $jsVal = "'" + $escaped + "'"
    }
    $sep = ','
    if ($i -eq $pairs.Count - 1) { $sep = '' }
    [void]$sb.AppendLine('  ' + $k + ': ' + $jsVal + $sep)
}
[void]$sb.AppendLine('};')

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

$count = $pairs.Count
$plural = ''
if ($count -ne 1) { $plural = 's' }
Write-Host "  + Synced .env -> js/env.local.js ($count var$plural)"
